#!/usr/bin/env python3
"""bughunt.py — zero-dependency toolkit for the bughunt skill (python3 stdlib only).

Deterministic pre-pass + findings pipeline:

    census    map the target: languages, sizes, generated/vendored/tests detection
    hotspots  rank files by likelihood-of-defect (churn x complexity x recency x boundary x test gap)
    signals   pain-point pre-pass: aged TODOs, feature flags, config drift, long scripts
    deps      manifest/lockfile audit: unpinned, no lockfile, lock drift, typosquat shape
    merge     validate + fingerprint + dedupe + suppress + baseline-diff findings JSON (CI gate)
    render    findings JSON -> markdown / HTML / SARIF 2.1.0 reports
    diff      fingerprint-compare two findings JSON files

All subcommands emit JSON to stdout (render writes files). Progress goes to stderr.
Exit codes (merge): 0 clean, 1 new Critical/High, 2 new Medium/Low. Usage/IO errors: 3.

The findings contract lives in schema/finding.schema.json next to this file; the
validator below is the executable version of it.
"""

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

TOOL_NAME = "bughunt"
TOOL_VERSION = "2026-06-06.4"
SCHEMA_VERSION = "1.0"

LENSES = [
    "dataflow-taint", "state-lifecycle", "concurrency", "boundaries-numeric",
    "error-failure", "contract-spec", "auth-access", "logic-correctness",
    "resource-performance", "dx-pain", "product-ux", "dependency-supply", "data-migration",
]
SEVERITIES = ["Critical", "High", "Medium", "Low"]
IMPACT_CLASSES = [
    "security", "correctness", "reliability", "performance",
    "data-integrity", "dx", "ux", "supply-chain",
]
VERDICTS = ["upheld", "refuted", "uncertain"]

STATE_DIR = ".bughunt"

# ---------------------------------------------------------------------------
# shared helpers
# ---------------------------------------------------------------------------

EXCLUDED_DIRS = {
    ".git", ".hg", ".svn", "node_modules", "vendor", "venv", ".venv", "env",
    "__pycache__", ".mypy_cache", ".pytest_cache", ".ruff_cache", ".tox",
    "dist", "build", "out", ".next", ".nuxt", ".output", "target", "Pods",
    "DerivedData", "coverage", ".turbo", ".cache", STATE_DIR,
}

LANG_BY_EXT = {
    ".py": "python", ".rb": "ruby", ".js": "javascript", ".jsx": "javascript",
    ".mjs": "javascript", ".cjs": "javascript", ".ts": "typescript", ".tsx": "typescript",
    ".go": "go", ".rs": "rust", ".c": "c", ".h": "c", ".cc": "cpp", ".cpp": "cpp",
    ".hpp": "cpp", ".m": "objc", ".mm": "objc", ".swift": "swift", ".kt": "kotlin",
    ".kts": "kotlin", ".java": "java", ".scala": "scala", ".cs": "csharp",
    ".php": "php", ".sql": "sql", ".sh": "shell", ".bash": "shell", ".zsh": "shell",
    ".fish": "shell", ".pl": "perl", ".lua": "lua", ".dart": "dart", ".ex": "elixir",
    ".exs": "elixir", ".erl": "erlang", ".html": "html", ".css": "css", ".scss": "css",
    ".vue": "vue", ".svelte": "svelte", ".tf": "terraform", ".yaml": "yaml",
    ".yml": "yaml", ".json": "json", ".toml": "toml", ".md": "markdown",
}
CODE_LANGS = set(LANG_BY_EXT.values()) - {"yaml", "json", "toml", "markdown", "html", "css"}

GENERATED_MARKERS = re.compile(
    r"(generated by|do not edit|autogenerated|auto-generated|@generated)", re.I)
GENERATED_PATH = re.compile(r"(\.min\.|\.pb\.|_pb2\.|\.generated\.|/gen/|/generated/|\.lock$)")
VENDORED_PATH = re.compile(r"(^|/)(vendor|third_party|thirdparty|external)(/|$)")
TEST_PATH = re.compile(
    r"((^|/)(tests?|spec|specs|__tests__|testing)(/|$)|"
    r"(_test|\.test|\.spec|_spec)\.[a-z]+$|(^|/)test_[^/]+$)", re.I)

BOUNDARY_HINT = re.compile(
    r"(route|handler|controller|endpoint|api|server|http|request|webhook|"
    r"auth|login|session|token|oauth|sql|query|db|database|repository|"
    r"pars|decod|deserial|unmarshal|upload|import|exec|spawn|subprocess|"
    r"socket|ipc|migrat)", re.I)

BRANCH_TOKENS = re.compile(
    r"\b(if|else if|elif|for|while|case|when|catch|except|rescue|guard|match|switch)\b|&&|\|\||\?\s")


def log(msg, quiet=False):
    if not quiet:
        print(msg, file=sys.stderr)


def die(msg, code=3):
    print(f"bughunt: error: {msg}", file=sys.stderr)
    sys.exit(code)


def emit(obj):
    json.dump(obj, sys.stdout, indent=2, ensure_ascii=False)
    sys.stdout.write("\n")


def run_git(root, args, check=False):
    """Run git in root; return stdout or None when git/repo is unavailable."""
    try:
        res = subprocess.run(
            ["git", "-C", str(root)] + args,
            capture_output=True, text=True, timeout=120)
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None
    if res.returncode != 0:
        if check:
            die(f"git {' '.join(args)} failed: {res.stderr.strip()}")
        return None
    return res.stdout


def git_available(root):
    return run_git(root, ["rev-parse", "--is-inside-work-tree"]) is not None


def git_commit(root):
    out = run_git(root, ["rev-parse", "--short", "HEAD"])
    return out.strip() if out else None


def relpath(root, path):
    return Path(path).resolve().relative_to(Path(root).resolve()).as_posix()


def iter_files(root, extra_excludes=()):
    """Yield (abs_path, rel_posix) for files under root, skipping excluded dirs."""
    root = Path(root).resolve()
    extra = [e.rstrip("/") for e in extra_excludes]
    for dirpath, dirnames, filenames in os.walk(root):
        rel_dir = Path(dirpath).relative_to(root).as_posix()
        dirnames[:] = sorted(
            d for d in dirnames
            if d not in EXCLUDED_DIRS and not d.startswith(".")
            and not any(Path(rel_dir, d).as_posix().startswith(e) or
                        Path(rel_dir, d).match(e) for e in extra))
        for name in sorted(filenames):
            p = Path(dirpath) / name
            rel = p.relative_to(root).as_posix()
            if any(rel.startswith(e) or p.match(e) for e in extra):
                continue
            yield p, rel


def read_text(path, limit_bytes=2_000_000):
    try:
        if path.stat().st_size > limit_bytes:
            return None
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


def now_iso():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ---------------------------------------------------------------------------
# census
# ---------------------------------------------------------------------------

# Side-effect tokens that disqualify a function from the "pure" shortlist.
IMPURE_PY = re.compile(
    r"\b(open|print|input|requests|urllib|subprocess|os\.|sys\.|random|"
    r"datetime\.now|time\.|global |nonlocal |self\.|cls\.|\.write|\.save|"
    r"db\.|session\.|cursor|logging)\b")
IMPURE_JS = re.compile(
    r"\b(fetch|console\.|document\.|window\.|process\.|require\(|fs\.|"
    r"this\.|await |Math\.random|Date\.|localStorage|axios|setTimeout|setInterval)\b")

PY_DEF = re.compile(r"^def\s+([A-Za-z_]\w*)\s*\(([^)]*)\)", re.M)
JS_FUNC = re.compile(
    r"^(?:export\s+)?(?:function\s+([A-Za-z_$][\w$]*)\s*\(([^)]*)\)|"
    r"(?:const|let)\s+([A-Za-z_$][\w$]*)\s*=\s*(?:\(([^)]*)\)|[\w$]+)\s*=>)", re.M)


def detect_flags(rel, text, first_lines):
    generated = bool(GENERATED_PATH.search(rel)) or bool(GENERATED_MARKERS.search(first_lines))
    vendored = bool(VENDORED_PATH.search(rel))
    tests = bool(TEST_PATH.search(rel))
    return generated, vendored, tests


def find_functions(rel, lang, text):
    """Heuristic shortlist of pure-function candidates for /fuzz."""
    out = []
    lines = text.splitlines()
    if lang == "python":
        matches = list(PY_DEF.finditer(text))
        for i, m in enumerate(matches):
            start = text.count("\n", 0, m.start()) + 1
            end_off = matches[i + 1].start() if i + 1 < len(matches) else len(text)
            body = text[m.start():end_off]
            out.append({
                "file": rel, "name": m.group(1), "startLine": start,
                "endLine": start + body.count("\n"),
                "params": [p.strip().split(":")[0].split("=")[0].strip()
                           for p in m.group(2).split(",") if p.strip()],
                "pure_guess": not IMPURE_PY.search(body),
            })
    elif lang in ("javascript", "typescript"):
        for m in JS_FUNC.finditer(text):
            name = m.group(1) or m.group(3)
            params = m.group(2) if m.group(2) is not None else (m.group(4) or "")
            start = text.count("\n", 0, m.start()) + 1
            end = min(start + 60, len(lines))  # rough body window
            body = "\n".join(lines[start - 1:end])
            out.append({
                "file": rel, "name": name, "startLine": start, "endLine": end,
                "params": [p.strip().split(":")[0].split("=")[0].strip()
                           for p in params.split(",") if p.strip()],
                "pure_guess": not IMPURE_JS.search(body),
            })
    return out


def cmd_census(args):
    root = Path(args.root).resolve()
    files, languages, functions = [], {}, []
    totals = {"files": 0, "loc": 0, "bytes": 0, "codeFiles": 0, "testFiles": 0}
    for p, rel in iter_files(root, args.exclude):
        ext = p.suffix.lower()
        lang = LANG_BY_EXT.get(ext)
        try:
            size = p.stat().st_size
        except OSError:
            continue
        entry = {"path": rel, "lang": lang, "bytes": size, "loc": 0,
                 "generated": False, "vendored": False, "tests": False}
        if lang:
            text = read_text(p)
            if text is not None:
                entry["loc"] = text.count("\n") + (1 if text and not text.endswith("\n") else 0)
                first = "\n".join(text.splitlines()[:5])
                entry["generated"], entry["vendored"], entry["tests"] = detect_flags(rel, text, first)
                if (args.functions and lang in ("python", "javascript", "typescript")
                        and not entry["generated"] and not entry["vendored"] and not entry["tests"]):
                    functions.extend(find_functions(rel, lang, text))
            lstat = languages.setdefault(lang, {"files": 0, "loc": 0})
            lstat["files"] += 1
            lstat["loc"] += entry["loc"]
            if lang in CODE_LANGS:
                totals["codeFiles"] += 1
            if entry["tests"]:
                totals["testFiles"] += 1
        totals["files"] += 1
        totals["loc"] += entry["loc"]
        totals["bytes"] += size
        files.append(entry)
    out = {"root": str(root), "commit": git_commit(root), "files": files,
           "languages": languages, "totals": totals}
    if args.functions:
        out["functions"] = [f for f in functions if f["pure_guess"]] or functions[:50]
    emit(out)


# ---------------------------------------------------------------------------
# hotspots
# ---------------------------------------------------------------------------

WEIGHTS = {"churn": 0.30, "complexity": 0.25, "recency": 0.15, "boundary": 0.20, "test_gap": 0.10}


def git_churn_recency(root, since=None):
    """One pass over `git log --name-only` -> {rel: churn}, {rel: last_touch_epoch}."""
    cmd = ["log", "--name-only", "--no-renames", "--pretty=format:\x01%ct"]
    if since:
        cmd.insert(1, f"--since={since}")
    out = run_git(root, cmd)
    if out is None:
        return None, None
    churn, last = {}, {}
    ts = None
    for line in out.splitlines():
        if line.startswith("\x01"):
            ts = int(line[1:]) if line[1:].isdigit() else ts
        elif line.strip():
            churn[line] = churn.get(line, 0) + 1
            if line not in last and ts:  # log is newest-first
                last[line] = ts
    return churn, last


def complexity_proxy(text):
    lines = text.splitlines()
    branches = sum(len(BRANCH_TOKENS.findall(ln)) for ln in lines)
    max_indent = 0
    for ln in lines:
        stripped = ln.lstrip(" \t")
        if not stripped:
            continue
        indent = len(ln) - len(stripped)
        max_indent = max(max_indent, indent)
    return branches + max_indent // 2 + len(lines) // 40


def cmd_hotspots(args):
    root = Path(args.root).resolve()
    churn, last_touch = git_churn_recency(root, args.since)
    use_git = churn is not None
    now = datetime.now(timezone.utc).timestamp()

    candidates = []
    test_stems = set()
    rows = []
    for p, rel in iter_files(root, args.exclude):
        lang = LANG_BY_EXT.get(p.suffix.lower())
        if not lang or lang not in CODE_LANGS:
            continue
        text = read_text(p)
        if text is None:
            continue
        first = "\n".join(text.splitlines()[:5])
        generated, vendored, tests = detect_flags(rel, text, first)
        if generated or vendored:
            continue
        if tests:
            test_stems.add(Path(rel).stem.replace(".test", "").replace(".spec", "")
                           .removeprefix("test_").removesuffix("_test").removesuffix("_spec"))
            continue
        rows.append((p, rel, text))

    for p, rel, text in rows:
        comp = complexity_proxy(text)
        boundary = 1 if (BOUNDARY_HINT.search(rel) or BOUNDARY_HINT.search(text[:4000])) else 0
        test_gap = 0 if Path(rel).stem in test_stems else 1
        if use_git:
            c = churn.get(rel, 0)
            recency_days = (now - last_touch.get(rel, 0)) / 86400 if rel in last_touch else None
        else:
            c = 0
            try:
                recency_days = (now - p.stat().st_mtime) / 86400
            except OSError:
                recency_days = None
        candidates.append({"path": rel, "churn": c, "complexity": comp,
                           "recency_days": round(recency_days, 1) if recency_days is not None else None,
                           "boundary": boundary, "test_gap": test_gap})

    max_churn = max((c["churn"] for c in candidates), default=0) or 1
    max_comp = max((c["complexity"] for c in candidates), default=0) or 1
    for c in candidates:
        recency_boost = 0.0
        if c["recency_days"] is not None:
            recency_boost = max(0.0, 1.0 - min(c["recency_days"], 365) / 365)
        score = (WEIGHTS["churn"] * (c["churn"] / max_churn)
                 + WEIGHTS["complexity"] * (c["complexity"] / max_comp)
                 + WEIGHTS["recency"] * recency_boost
                 + WEIGHTS["boundary"] * c["boundary"]
                 + WEIGHTS["test_gap"] * c["test_gap"])
        c["score"] = round(score, 4)
        reasons = []
        if c["churn"] >= max_churn * 0.5 and c["churn"] > 1:
            reasons.append(f"high churn ({c['churn']} commits)")
        if c["complexity"] >= max_comp * 0.5:
            reasons.append(f"complex (proxy {c['complexity']})")
        if recency_boost > 0.7:
            reasons.append("recently touched")
        if c["boundary"]:
            reasons.append("at a trust boundary")
        if c["test_gap"]:
            reasons.append("no matching test file")
        c["reasons"] = reasons

    candidates.sort(key=lambda c: -c["score"])
    emit({"gitAvailable": use_git, "weights": WEIGHTS,
          "hotspots": candidates[: args.top]})


# ---------------------------------------------------------------------------
# signals
# ---------------------------------------------------------------------------

MARKER_RE = re.compile(r"\b(TODO|FIXME|HACK|XXX)\b[:\s]?(.{0,120})")
FLAG_RE = re.compile(
    r"(feature[_-]?flag|featureFlag|FeatureFlag|flags?\.[A-Za-z_][\w]*|"
    r"isEnabled\(|is_enabled\(|\.enabled\b|toggle[s]?\.[A-Za-z_])")
ENV_KEY_RE = re.compile(r"^\s*(?:export\s+)?([A-Z][A-Z0-9_]+)\s*=", re.M)


def blame_age_days(root, rel, line_no):
    out = run_git(root, ["blame", "-L", f"{line_no},{line_no}", "--line-porcelain", "--", rel])
    if not out:
        return None, None
    author, ts = None, None
    for ln in out.splitlines():
        if ln.startswith("author "):
            author = ln[7:]
        elif ln.startswith("author-time "):
            ts = int(ln.split()[1])
    if ts is None:
        return None, author
    days = (datetime.now(timezone.utc).timestamp() - ts) / 86400
    return round(days), author


def cmd_signals(args):
    root = Path(args.root).resolve()
    use_git = git_available(root)
    todos, flags, config_drift, long_scripts = [], [], [], []
    blames_left = 400  # hard cap so huge repos stay fast

    for p, rel in iter_files(root, args.exclude):
        lang = LANG_BY_EXT.get(p.suffix.lower())
        if not lang:
            continue
        text = read_text(p)
        if text is None:
            continue
        first = "\n".join(text.splitlines()[:5])
        generated, vendored, _ = detect_flags(rel, text, first)
        if generated or vendored:
            continue
        for i, line in enumerate(text.splitlines(), 1):
            m = MARKER_RE.search(line)
            if m and lang in CODE_LANGS:
                age, author = (None, None)
                if use_git and blames_left > 0:
                    age, author = blame_age_days(root, rel, i)
                    blames_left -= 1
                todos.append({"file": rel, "line": i, "kind": m.group(1),
                              "text": m.group(2).strip(), "ageDays": age, "author": author,
                              "aged": bool(age and age >= args.max_age_days)})
            fm = FLAG_RE.search(line)
            if fm and lang in CODE_LANGS:
                flags.append({"file": rel, "line": i, "ref": fm.group(0)})
        if lang == "shell" and text.count("\n") > 300:
            long_scripts.append({"path": rel, "kind": "shell",
                                 "note": f"{text.count(chr(10))} lines; consider splitting or profiling"})

    # config drift: .env.example vs .env / .env.local
    example = root / ".env.example"
    if example.exists():
        ex_keys = set(ENV_KEY_RE.findall(example.read_text(errors="replace")))
        for actual_name in (".env", ".env.local"):
            actual = root / actual_name
            if actual.exists():
                ac_keys = set(ENV_KEY_RE.findall(actual.read_text(errors="replace")))
                for k in sorted(ex_keys - ac_keys):
                    config_drift.append({"file": actual_name, "key": k,
                                         "note": "declared in .env.example but missing here"})
                for k in sorted(ac_keys - ex_keys):
                    config_drift.append({"file": ".env.example", "key": k,
                                         "note": f"present in {actual_name} but undocumented in .env.example"})

    # package.json scripts that chain many commands serially
    pkg = root / "package.json"
    if pkg.exists():
        try:
            scripts = json.loads(pkg.read_text(errors="replace")).get("scripts", {})
            for name, body in scripts.items():
                if isinstance(body, str) and body.count("&&") >= 3:
                    long_scripts.append({"path": f"package.json#scripts.{name}", "kind": "npm-script",
                                         "note": f"chains {body.count('&&') + 1} serial commands"})
        except (json.JSONDecodeError, OSError):
            pass

    flags = flags[:300]
    emit({"gitAvailable": use_git, "maxAgeDays": args.max_age_days,
          "todos": todos, "flags": flags, "configDrift": config_drift,
          "longScripts": long_scripts})


# ---------------------------------------------------------------------------
# deps
# ---------------------------------------------------------------------------

POPULAR_PACKAGES = {
    # npm
    "react", "react-dom", "express", "lodash", "axios", "next", "vue", "moment",
    "chalk", "commander", "typescript", "webpack", "vite", "jest", "eslint",
    "prettier", "zod", "prisma", "dotenv", "uuid", "classnames", "dayjs",
    # pypi
    "requests", "numpy", "pandas", "flask", "django", "pytest", "pydantic",
    "sqlalchemy", "boto3", "click", "rich", "httpx", "fastapi", "celery",
    # crates / go (by basename)
    "serde", "tokio", "clap", "anyhow", "rand", "regex", "cobra", "gin",
}
KNOWN_DEPRECATED = {"request", "node-sass", "tslint", "gulp-util", "left-pad", "istanbul", "moment"}
EXACT_NPM = re.compile(r"^\d+\.\d+\.\d+([-+].*)?$")


def edit_distance_one(a, b):
    if a == b:
        return False
    la, lb = len(a), len(b)
    if abs(la - lb) > 1:
        return False
    if la == lb:  # substitution or adjacent transposition
        diffs = [i for i in range(la) if a[i] != b[i]]
        if len(diffs) == 1:
            return True
        return (len(diffs) == 2 and diffs[1] == diffs[0] + 1
                and a[diffs[0]] == b[diffs[1]] and a[diffs[1]] == b[diffs[0]])
    short, long_ = (a, b) if la < lb else (b, a)
    i = j = edits = 0
    while i < len(short) and j < len(long_):
        if short[i] != long_[j]:
            edits += 1
            if edits > 1:
                return False
            j += 1
        else:
            i += 1
            j += 1
    return True


def parse_npm(root, deps, ecosystems):
    pkg = root / "package.json"
    if not pkg.exists():
        return
    try:
        data = json.loads(pkg.read_text(errors="replace"))
    except json.JSONDecodeError:
        return
    lock = next((root / n for n in
                 ("package-lock.json", "yarn.lock", "pnpm-lock.yaml", "bun.lockb")
                 if (root / n).exists()), None)
    ecosystems.append({"manager": "npm", "manifest": "package.json",
                       "lockfile": lock.name if lock else None, "locked": lock is not None})
    locked_names = set()
    if lock and lock.name == "package-lock.json":
        try:
            lock_data = json.loads(lock.read_text(errors="replace"))
            for key in lock_data.get("packages", {}):
                if key.startswith("node_modules/"):
                    locked_names.add(key.split("node_modules/")[-1])
            locked_names.update(lock_data.get("dependencies", {}).keys())
        except json.JSONDecodeError:
            pass
    for section, direct in (("dependencies", True), ("devDependencies", True)):
        for name, ver in (data.get(section) or {}).items():
            issues = []
            if not EXACT_NPM.match(str(ver)):
                issues.append("UNPINNED")
            if lock is None:
                issues.append("NO_LOCKFILE")
            elif locked_names and name not in locked_names:
                issues.append("LOCK_DRIFT")
            if name in KNOWN_DEPRECATED:
                issues.append("DEPRECATED_MARKER")
            squat = next((p for p in POPULAR_PACKAGES if edit_distance_one(name, p)), None)
            if squat:
                issues.append("TYPOSQUAT_SHAPE")
            deps.append({"name": name, "version": str(ver), "manager": "npm",
                         "pinned": bool(EXACT_NPM.match(str(ver))), "direct": direct,
                         "issues": issues,
                         **({"typosquatOf": squat} if squat else {})})


PY_REQ = re.compile(r"^\s*([A-Za-z0-9_.\-]+)\s*(\[[^\]]*\])?\s*([=<>!~]{1,2}\s*[\w.*]+)?")


def parse_python(root, deps, ecosystems):
    req = root / "requirements.txt"
    pyproject = root / "pyproject.toml"
    manifest = req if req.exists() else (pyproject if pyproject.exists() else None)
    if manifest is None:
        return
    lock = next((root / n for n in ("poetry.lock", "uv.lock", "Pipfile.lock")
                 if (root / n).exists()), None)
    ecosystems.append({"manager": "pip", "manifest": manifest.name,
                       "lockfile": lock.name if lock else None, "locked": lock is not None})
    names = []
    if manifest is req:
        for line in req.read_text(errors="replace").splitlines():
            line = line.split("#")[0].strip()
            if not line or line.startswith("-"):
                continue
            m = PY_REQ.match(line)
            if m:
                names.append((m.group(1), m.group(3) or ""))
    else:
        in_deps = False
        for line in pyproject.read_text(errors="replace").splitlines():
            if re.match(r"\s*dependencies\s*=\s*\[", line):
                in_deps = True
                continue
            if in_deps:
                if "]" in line and "\"" not in line.split("]")[0]:
                    in_deps = False
                    continue
                for spec in re.findall(r'"([^"]+)"', line):
                    m = PY_REQ.match(spec)
                    if m:
                        names.append((m.group(1), m.group(3) or ""))
                if line.strip().endswith("]"):
                    in_deps = False
    for name, ver in names:
        pinned = ver.strip().startswith("==")
        issues = [] if pinned else ["UNPINNED"]
        if lock is None and manifest is not req:
            issues.append("NO_LOCKFILE")
        squat = next((p for p in POPULAR_PACKAGES if edit_distance_one(name.lower(), p)), None)
        if squat:
            issues.append("TYPOSQUAT_SHAPE")
        deps.append({"name": name, "version": ver.strip(), "manager": "pip",
                     "pinned": pinned, "direct": True, "issues": issues,
                     **({"typosquatOf": squat} if squat else {})})


def query_osv(deps, quiet):
    import urllib.request
    eco_map = {"npm": "npm", "pip": "PyPI"}
    queries = [{"package": {"name": d["name"], "ecosystem": eco_map[d["manager"]]},
                **({"version": d["version"]} if d.get("pinned") else {})}
               for d in deps if d["manager"] in eco_map]
    if not queries:
        return []
    body = json.dumps({"queries": queries}).encode()
    req = urllib.request.Request(
        "https://api.osv.dev/v1/querybatch", data=body,
        headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            results = json.loads(resp.read()).get("results", [])
    except Exception as e:  # fail-soft: offline checks still stand
        log(f"OSV query failed ({e}); continuing offline", quiet)
        return []
    advisories = []
    for d, res in zip([d for d in deps if d["manager"] in eco_map], results):
        for vuln in res.get("vulns", []) or []:
            advisories.append({"name": d["name"], "id": vuln.get("id"),
                               "severity": (vuln.get("database_specific") or {}).get("severity"),
                               "source": "osv.dev"})
    return advisories


def cmd_deps(args):
    root = Path(args.root).resolve()
    deps, ecosystems = [], []
    parse_npm(root, deps, ecosystems)
    parse_python(root, deps, ecosystems)
    lock_drift = [{"name": d["name"], "note": "in manifest but not in lockfile"}
                  for d in deps if "LOCK_DRIFT" in d["issues"]]
    advisories = query_osv(deps, args.quiet) if args.osv else []
    emit({"ecosystems": ecosystems, "deps": deps, "lockDrift": lock_drift,
          "advisories": advisories, "osvQueried": bool(args.osv)})


# ---------------------------------------------------------------------------
# merge — validate + fingerprint + dedupe + suppress + baseline + gate
# ---------------------------------------------------------------------------

LITERAL_RE = re.compile(r"\"[^\"]*\"|'[^']*'|`[^`]*`|\b\d[\d_.xa-fA-F]*\b")


def normalize_snippet(lines):
    joined = " ".join(ln.strip() for ln in lines if ln.strip())
    joined = LITERAL_RE.sub("§", joined)
    return re.sub(r"\s+", " ", joined).strip()


def fingerprint(root, finding):
    lens = finding["lens"]
    rel = finding["location"]["file"]
    start = finding["location"]["startLine"]
    end = finding["location"].get("endLine", start)
    snippet = None
    path = Path(root) / rel
    text = read_text(path) if path.exists() else None
    if text is not None:
        lines = text.splitlines()[start - 1:end]
        if lines:
            snippet = normalize_snippet(lines)
    basis = snippet if snippet else finding["title"]
    digest = hashlib.sha256(f"{lens}\x00{rel}\x00{basis}".encode()).hexdigest()
    return digest[:16]


def validate_finding(f, idx, errors):
    """Executable version of schema/finding.schema.json. Returns cleaned finding or None."""
    where = f"finding[{idx}]"
    if not isinstance(f, dict):
        errors.append(f"{where}: not an object")
        return None
    required = ["title", "lens", "severity", "confidence", "location", "trigger", "trace", "impact"]
    missing = [k for k in required if k not in f or f[k] in (None, "")]
    if missing:
        errors.append(f"{where} ({f.get('title', '?')}): missing {', '.join(missing)}")
        return None
    if f["lens"] not in LENSES:
        errors.append(f"{where}: unknown lens '{f['lens']}'")
        return None
    if f["severity"] not in SEVERITIES:
        errors.append(f"{where}: invalid severity '{f['severity']}'")
        return None
    try:
        conf = float(f["confidence"])
    except (TypeError, ValueError):
        errors.append(f"{where}: confidence not a number")
        return None
    if not 0.0 <= conf <= 1.0:
        errors.append(f"{where}: confidence {conf} out of [0,1]")
        return None
    f["confidence"] = conf
    loc = f["location"]
    if not isinstance(loc, dict) or "file" not in loc or "startLine" not in loc:
        errors.append(f"{where}: location needs file + startLine")
        return None
    try:
        loc["startLine"] = int(loc["startLine"])
        loc["endLine"] = int(loc.get("endLine", loc["startLine"]))
    except (TypeError, ValueError):
        errors.append(f"{where}: location lines not integers")
        return None
    if f.get("impactClass") and f["impactClass"] not in IMPACT_CLASSES:
        errors.append(f"{where}: invalid impactClass '{f['impactClass']}' (defaulted)")
        f["impactClass"] = None
    if f.get("verified") and f["verified"].get("verdict") not in VERDICTS:
        errors.append(f"{where}: invalid verified.verdict (cleared)")
        f["verified"] = None
    return f


def confidence_label(conf):
    return "Confirmed" if conf >= 0.85 else ("Probable" if conf >= 0.5 else "Speculative")


def overlaps(a, b, slack=5):
    a1, a2 = a["location"]["startLine"], a["location"].get("endLine", a["location"]["startLine"])
    b1, b2 = b["location"]["startLine"], b["location"].get("endLine", b["location"]["startLine"])
    return a["location"]["file"] == b["location"]["file"] and a1 <= b2 + slack and b1 <= a2 + slack


def cross_lens_cluster(findings, enabled, slack=1):
    """Collapse the SAME bug reported by different lenses at overlapping lines into one
    primary finding (+ alsoFlaggedBy), boosting confidence for the convergence. Same-lens
    findings are never merged (fingerprint dedupe already handled exact repeats). When
    disabled, fall back to the legacy behavior: boost confidence on overlap, keep all."""
    if not enabled:
        for i, a in enumerate(findings):
            for b in findings[i + 1:]:
                if a["lens"] != b["lens"] and overlaps(a, b, slack):
                    for x in (a, b):
                        if "cross-validated" not in (x.get("tags") or []):
                            x["confidence"] = min(0.99, x["confidence"] + 0.15)
                            x["confidenceLabel"] = confidence_label(x["confidence"])
                            x.setdefault("tags", []).append("cross-validated")
        return findings

    # Union-find over cross-lens overlap edges only (distinct lenses + overlapping lines).
    parent = list(range(len(findings)))

    def find(i):
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    for i, a in enumerate(findings):
        for j in range(i + 1, len(findings)):
            b = findings[j]
            if a["lens"] != b["lens"] and overlaps(a, b, slack):
                parent[find(i)] = find(j)

    groups = {}
    for i in range(len(findings)):
        groups.setdefault(find(i), []).append(findings[i])

    sev_rank = {s: i for i, s in enumerate(SEVERITIES)}
    out = []
    for members in groups.values():
        if len(members) == 1:
            out.append(members[0])
            continue
        primary = min(members, key=lambda x: (sev_rank[x["severity"]], -x["confidence"],
                                              -len(x.get("trace", ""))))
        others = [x for x in members if x is not primary]
        lenses = {x["lens"] for x in members}
        if len(lenses) > 1:  # genuine cross-lens convergence is strong signal
            primary["confidence"] = min(0.99, primary["confidence"] + 0.1 * len(others))
            primary["confidenceLabel"] = confidence_label(primary["confidence"])
            primary.setdefault("tags", [])
            if "cross-validated" not in primary["tags"]:
                primary["tags"].append("cross-validated")
        primary["alsoFlaggedBy"] = [
            {"lens": x["lens"], "title": x["title"], "severity": x["severity"],
             "confidence": round(x["confidence"], 2),
             "line": x["location"]["startLine"]} for x in others]
        out.append(primary)
    return out


def load_json_file(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, json.JSONDecodeError) as e:
        die(f"cannot read {path}: {e}")


def cmd_merge(args):
    root = Path(args.root).resolve()
    docs = []
    for src in args.inputs:
        if src == "-":
            try:
                docs.append(json.load(sys.stdin))
            except json.JSONDecodeError as e:
                die(f"stdin is not valid JSON: {e}")
        else:
            docs.append(load_json_file(src))

    run_meta, raw = None, []
    for doc in docs:
        if isinstance(doc, list):  # tolerate a bare findings array
            raw.extend(doc)
            continue
        if run_meta is None and doc.get("run"):
            run_meta = doc["run"]
        raw.extend(doc.get("findings", []))

    errors = []
    findings = [v for i, f in enumerate(raw) if (v := validate_finding(f, i, errors))]
    n_dropped = len(raw) - len(findings)
    for e in errors:
        log(f"  invalid: {e}", args.quiet)

    # normalize + fingerprint
    for f in findings:
        f.setdefault("impactClass", None)
        f["impactClass"] = f["impactClass"] or "correctness"
        if not re.fullmatch(r"[0-9a-f]{16}", str(f.get("fingerprint") or "")):
            f["fingerprint"] = fingerprint(root, f)
        f["confidenceLabel"] = confidence_label(f["confidence"])

    # quarantine refuted
    refuted = [f for f in findings if (f.get("verified") or {}).get("verdict") == "refuted"]
    refuted_ids = {id(f) for f in refuted}
    findings = [f for f in findings if id(f) not in refuted_ids]

    # dedupe identical fingerprints (same lens + site)
    by_fp = {}
    for f in findings:
        prev = by_fp.get(f["fingerprint"])
        if prev is None:
            by_fp[f["fingerprint"]] = f
        else:  # keep the clearer write-up: higher confidence, then longer trace
            keep = max(prev, f, key=lambda x: (x["confidence"], len(x.get("trace", ""))))
            by_fp[f["fingerprint"]] = keep
    findings = list(by_fp.values())
    n_before_cluster = len(findings)

    # cross-lens clustering: the same bug seen by multiple lenses collapses to one primary
    # finding (+ alsoFlaggedBy), with a confidence boost for the convergence.
    findings = cross_lens_cluster(findings, enabled=not args.no_cluster)
    n_clustered = n_before_cluster - len(findings)

    # suppressions
    sup_path = Path(args.suppress) if args.suppress else root / STATE_DIR / "suppressions.json"
    suppressed_fps = {}
    if sup_path.exists():
        sup_doc = load_json_file(sup_path)
        for entry in sup_doc.get("suppressions", []):
            suppressed_fps[entry.get("fingerprint")] = entry.get("reason", "")
    n_suppressed = 0
    for f in findings:
        f["suppressed"] = f["fingerprint"] in suppressed_fps
        if f["suppressed"]:
            f["suppressedReason"] = suppressed_fps[f["fingerprint"]]
            n_suppressed += 1

    # baseline diff
    base_path = Path(args.baseline) if args.baseline else root / STATE_DIR / "baseline.json"
    baseline_fps = {}
    if base_path.exists():
        base_doc = load_json_file(base_path)
        baseline_fps = {e["fingerprint"]: e for e in base_doc.get("findings", [])}
    fixed = []
    current_fps = {f["fingerprint"] for f in findings}
    for f in findings:
        f["baselineStatus"] = "existing" if f["fingerprint"] in baseline_fps else "new"
    if baseline_fps:
        fixed = [{"fingerprint": fp, "id": e.get("id"), "title": e.get("title"),
                  "lens": e.get("lens"), "severity": e.get("severity"),
                  "file": e.get("file")} for fp, e in baseline_fps.items()
                 if fp not in current_fps]

    # stable order + renumber ids
    sev_rank = {s: i for i, s in enumerate(SEVERITIES)}
    findings.sort(key=lambda f: (sev_rank[f["severity"]], -f["confidence"], f["location"]["file"]))
    for i, f in enumerate(findings, 1):
        f["id"] = f"BH-{i:03d}"

    new_active = [f for f in findings if f["baselineStatus"] == "new" and not f["suppressed"]]
    n_new_crit = sum(1 for f in new_active if f["severity"] in ("Critical", "High"))
    n_new_other = len(new_active) - n_new_crit

    out = {
        "schemaVersion": SCHEMA_VERSION,
        "tool": {"name": TOOL_NAME, "version": TOOL_VERSION},
        "run": run_meta or {"root": str(root), "commit": git_commit(root),
                            "finishedAt": now_iso()},
        "findings": findings,
        "refuted": refuted,
        "baselineDiff": {
            "baselinePresent": bool(baseline_fps),
            "new": [f["id"] for f in findings if f["baselineStatus"] == "new"],
            "existing": [f["id"] for f in findings if f["baselineStatus"] == "existing"],
            "fixed": fixed,
        },
        "summary": {
            "total": len(findings),
            "bySeverity": {s: sum(1 for f in findings if f["severity"] == s) for s in SEVERITIES},
            "byImpactClass": {c: n for c in IMPACT_CLASSES
                              if (n := sum(1 for f in findings if f["impactClass"] == c))},
            "new": len([f for f in findings if f["baselineStatus"] == "new"]),
            "fixed": len(fixed),
            "suppressed": n_suppressed,
            "refuted": len(refuted),
            "clustered": n_clustered,
            "invalidDropped": n_dropped,
        },
    }

    out_path = Path(args.out) if args.out else root / STATE_DIR / "findings.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    if args.write_baseline:
        base_entries = [{"fingerprint": f["fingerprint"], "id": f["id"], "title": f["title"],
                         "lens": f["lens"], "severity": f["severity"],
                         "file": f["location"]["file"]} for f in findings]
        base_path.parent.mkdir(parents=True, exist_ok=True)
        base_path.write_text(json.dumps(
            {"schemaVersion": SCHEMA_VERSION, "writtenAt": now_iso(),
             "findings": base_entries}, indent=2) + "\n", encoding="utf-8")

    s = out["summary"]
    log(f"{s['total']} total, {s['new']} new, {s['fixed']} fixed, "
        f"{s['suppressed']} suppressed, {s['refuted']} refuted "
        f"({n_new_crit} new critical/high) -> {out_path}", args.quiet)
    emit(out)

    if args.fail_on == "none":
        sys.exit(0)
    if n_new_crit and args.fail_on in ("critical-high", "any"):
        sys.exit(1)
    if n_new_other and args.fail_on == "any":
        sys.exit(2)
    if n_new_other and args.fail_on == "critical-high":
        sys.exit(2)
    sys.exit(0)


# ---------------------------------------------------------------------------
# render — markdown / HTML / SARIF
# ---------------------------------------------------------------------------

def md_finding(f):
    sev_conf = f"[{f['severity']}-{f['confidenceLabel']}]"
    lines = [f"### {sev_conf} {f['title']}",
             f"- **ID:** {f['id']}",
             f"- **Location:** {f['location']['file']}:{f['location']['startLine']}",
             f"- **Lens:** {f['lens']}",
             f"- **Severity:** {f['severity']}",
             f"- **Confidence:** {f['confidenceLabel']}"]
    if f.get("impactClass") and f["impactClass"] != "correctness":
        lines.append(f"- **Impact class:** {f['impactClass']}")
    lines += [f"- **Trigger:** {f['trigger']}",
              f"- **Trace:** {f['trace']}",
              f"- **Impact:** {f['impact']}",
              f"- **Repro:** {f.get('repro') or 'not reproduced: static finding'}",
              f"- **Fix sketch:** {f.get('fixSketch') or '—'}"]
    if f.get("alsoFlaggedBy"):
        also = ", ".join(f"{x['lens']} (line {x['line']})" for x in f["alsoFlaggedBy"])
        lines.append(f"- **Also flagged by:** {also} — cross-lens convergence")
    if (f.get("verified") or {}).get("verdict"):
        v = f["verified"]
        note = f" — {v['note']}" if v.get("note") else ""
        lines.append(f"- **Verified:** {v['verdict']} (via {v.get('by', 'verify')}){note}")
    lines.append(f"- **Fingerprint:** `{f['fingerprint']}`")
    return "\n".join(lines)


def render_md(doc):
    run = doc.get("run") or {}
    s = doc.get("summary") or {}
    bd = doc.get("baselineDiff") or {}
    date = (run.get("finishedAt") or now_iso())[:10]
    target = run.get("target") or Path(run.get("root", ".")).name
    sev = s.get("bySeverity", {})
    findings = doc.get("findings", [])
    active = [f for f in findings if not f.get("suppressed")]
    main = [f for f in active if f["confidenceLabel"] in ("Confirmed", "Probable")]
    spec = [f for f in active if f["confidenceLabel"] == "Speculative"]
    n_conf = sum(1 for f in active if f["confidenceLabel"] == "Confirmed")
    n_prob = sum(1 for f in active if f["confidenceLabel"] == "Probable")

    out = [f"# Bug report — {target} — {date}", "", "## Summary",
           f"{len(active)} findings: {sev.get('Critical', 0)} critical, {sev.get('High', 0)} high, "
           f"{sev.get('Medium', 0)} medium, {sev.get('Low', 0)} low. "
           f"{n_conf} confirmed, {n_prob} probable, {len(spec)} speculative."]
    if main:
        top = main[0]
        out.append(f"Headline: {top['title']} ({top['location']['file']}:{top['location']['startLine']}).")
    if bd.get("baselinePresent"):
        out += ["", "## Baseline diff",
                f"**{s.get('new', 0)} new**, **{s.get('fixed', 0)} fixed**, "
                f"{s.get('suppressed', 0)} suppressed since the last baselined run."]
        for e in bd.get("fixed", []):
            out.append(f"- fixed: {e.get('title')} ({e.get('file')}) `{e.get('fingerprint')}`")
    out += ["", "## Confirmed & Probable findings", ""]
    out += [md_finding(f) + "\n" for f in main] or ["None.", ""]
    out += ["## Speculative (needs a human eye)", ""]
    out += [md_finding(f) + "\n" for f in spec] or ["None.", ""]
    suppressed = [f for f in findings if f.get("suppressed")]
    if suppressed:
        out += ["## Suppressed", ""]
        out += [f"- {f['id']} {f['title']} `{f['fingerprint']}` — {f.get('suppressedReason') or 'suppressed'}"
                for f in suppressed] + [""]
    refuted = doc.get("refuted", [])
    if refuted:
        out += ["## Refuted (appendix)",
                "Candidates the adversarial verify pass killed — kept for transparency.", ""]
        out += [f"- {f['title']} ({f['location']['file']}:{f['location']['startLine']}) — "
                f"{(f.get('verified') or {}).get('note') or 'refuted'}" for f in refuted] + [""]
    out += ["## Coverage & gaps"]
    lenses = run.get("lenses") or sorted({f["lens"] for f in findings})
    files = sorted({f["location"]["file"] for f in findings})
    cov = f"Hunted with lenses: {', '.join(lenses) if lenses else 'unknown'}."
    scope = (run.get("scope") or {}).get("mode")
    if scope:
        cov += f" Scope: {scope}."
    out.append(cov)
    if files:
        out.append(f"Findings span {len(files)} file(s): {', '.join(files[:12])}"
                   f"{' …' if len(files) > 12 else ''}.")
    out += ["", "## Recommended next step"]
    if main:
        ids = "/".join(f["id"] for f in main[:3])
        out.append(f"Fix {ids} first, then run `/review` (autoreview) before merging.")
    else:
        out.append("No confirmed/probable findings — consider widening scope or lenses.")
    return "\n".join(out) + "\n"


SEV_COLOR = {"Critical": "#d13438", "High": "#e8893c", "Medium": "#e3c54b", "Low": "#7aa2f7"}


def render_html(doc):
    md_ish = render_md(doc)  # reuse ordering; render simple styled cards
    run = doc.get("run") or {}
    target = run.get("target") or Path(run.get("root", ".")).name
    s = doc.get("summary") or {}
    rows = []
    for f in doc.get("findings", []):
        if f.get("suppressed"):
            continue
        color = SEV_COLOR.get(f["severity"], "#888")
        v = (f.get("verified") or {}).get("verdict", "")
        rows.append(f"""
  <details class="f" style="border-left:4px solid {color}">
    <summary><span class="sev" style="background:{color}">{f['severity']}</span>
      <span class="conf">{f['confidenceLabel']}</span> {f['title']}
      <code>{f['location']['file']}:{f['location']['startLine']}</code></summary>
    <dl>
      <dt>Lens</dt><dd>{f['lens']} · impact class: {f.get('impactClass', 'correctness')}</dd>
      <dt>Trigger</dt><dd>{f['trigger']}</dd>
      <dt>Trace</dt><dd>{f['trace']}</dd>
      <dt>Impact</dt><dd>{f['impact']}</dd>
      <dt>Repro</dt><dd>{f.get('repro') or 'not reproduced: static finding'}</dd>
      <dt>Fix sketch</dt><dd>{f.get('fixSketch') or '—'}</dd>
      <dt>Verified</dt><dd>{v or 'n/a'}</dd>
      <dt>Fingerprint</dt><dd><code>{f['fingerprint']}</code> · {f.get('baselineStatus', '')}</dd>
    </dl>
  </details>""")
    sev = s.get("bySeverity", {})
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Bug report — {target}</title>
<style>
  body {{ font: 15px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         max-width: 920px; margin: 2rem auto; padding: 0 1rem; color: #1a1a2e; }}
  h1 {{ font-size: 1.5rem; }} code {{ background:#f2f2f7; padding:1px 5px; border-radius:4px; }}
  .stats span {{ display:inline-block; margin-right:1rem; font-weight:600; }}
  .f {{ margin: .8rem 0; padding: .6rem .9rem; background:#fafafc; border-radius:6px; }}
  .f summary {{ cursor:pointer; font-weight:600; }}
  .sev {{ color:#fff; border-radius:4px; padding:1px 8px; font-size:.8rem; }}
  .conf {{ color:#666; font-size:.85rem; margin-right:.4rem; }}
  dl {{ display:grid; grid-template-columns: 7.5rem 1fr; gap:.25rem .75rem; margin:.8rem 0 0; }}
  dt {{ font-weight:600; color:#555; }} dd {{ margin:0; }}
</style></head><body>
<h1>Bug report — {target}</h1>
<p class="stats"><span>{s.get('total', 0)} findings</span>
<span style="color:{SEV_COLOR['Critical']}">{sev.get('Critical', 0)} critical</span>
<span style="color:{SEV_COLOR['High']}">{sev.get('High', 0)} high</span>
<span>{sev.get('Medium', 0)} medium</span><span>{sev.get('Low', 0)} low</span>
<span>{s.get('new', 0)} new · {s.get('fixed', 0)} fixed · {s.get('suppressed', 0)} suppressed</span></p>
{''.join(rows) or '<p>No findings.</p>'}
<hr><pre style="white-space:pre-wrap; color:#555; font-size:.8rem">{md_ish}</pre>
</body></html>
"""


def render_sarif(doc):
    findings = [f for f in doc.get("findings", []) if not f.get("suppressed")]
    level = {"Critical": "error", "High": "error", "Medium": "warning", "Low": "note"}
    rules, seen = [], set()
    for f in findings:
        rule_id = f"bughunt/{f['lens']}"
        if rule_id not in seen:
            seen.add(rule_id)
            rules.append({
                "id": rule_id,
                "name": f["lens"],
                "shortDescription": {"text": f"bughunt {f['lens']} lens"},
                "helpUri": "https://github.com/robzilla1738/roberts-skills/tree/main/plugins/bughunt-suite",
            })
    results = [{
        "ruleId": f"bughunt/{f['lens']}",
        "level": level[f["severity"]],
        "message": {"text": f"{f['title']} — {f['impact']} (trigger: {f['trigger']})"},
        "locations": [{
            "physicalLocation": {
                "artifactLocation": {"uri": f["location"]["file"]},
                "region": {"startLine": f["location"]["startLine"],
                           "endLine": f["location"].get("endLine", f["location"]["startLine"])},
            }
        }],
        "partialFingerprints": {"bughuntFingerprint/v1": f["fingerprint"]},
        "properties": {"severity": f["severity"], "confidence": f["confidence"],
                       "impactClass": f.get("impactClass"), "id": f["id"]},
    } for f in findings]
    return {
        "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {"driver": {
                "name": TOOL_NAME, "version": TOOL_VERSION,
                "informationUri": "https://github.com/robzilla1738/roberts-skills/tree/main/plugins/bughunt-suite",
                "rules": rules,
            }},
            "results": results,
        }],
    }


def cmd_render(args):
    doc = json.load(sys.stdin) if args.input == "-" else load_json_file(args.input)
    root = Path(args.root).resolve()
    formats = [f.strip() for f in args.formats.split(",") if f.strip()]
    state = root / STATE_DIR
    state.mkdir(parents=True, exist_ok=True)
    written = []
    if "md" in formats:
        path = Path(args.md) if args.md else state / "report.md"
        path.write_text(render_md(doc), encoding="utf-8")
        written.append(str(path))
    if "html" in formats:
        path = Path(args.html) if args.html else state / "report.html"
        path.write_text(render_html(doc), encoding="utf-8")
        written.append(str(path))
    if "sarif" in formats:
        path = Path(args.sarif) if args.sarif else state / "report.sarif"
        path.write_text(json.dumps(render_sarif(doc), indent=2) + "\n", encoding="utf-8")
        written.append(str(path))
    log("wrote " + ", ".join(written), args.quiet)
    emit({"written": written})


# ---------------------------------------------------------------------------
# diff
# ---------------------------------------------------------------------------

def cmd_diff(args):
    a = load_json_file(args.a)
    b = load_json_file(args.b)
    fa = {f["fingerprint"]: f for f in a.get("findings", []) if f.get("fingerprint")}
    fb = {f["fingerprint"]: f for f in b.get("findings", []) if f.get("fingerprint")}
    new = [fb[fp].get("id") or fp for fp in fb.keys() - fa.keys()]
    fixed = [fa[fp].get("id") or fp for fp in fa.keys() - fb.keys()]
    unchanged = [fb[fp].get("id") or fp for fp in fa.keys() & fb.keys()]
    emit({"new": sorted(new), "fixed": sorted(fixed), "unchanged": sorted(unchanged),
          "counts": {"new": len(new), "fixed": len(fixed), "unchanged": len(unchanged)}})


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv=None):
    parser = argparse.ArgumentParser(prog="bughunt.py", description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", default=".", help="repo root (default: cwd)")
    parser.add_argument("--quiet", action="store_true", help="suppress stderr progress")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("census", help="map languages, sizes, generated/vendored/tests")
    p.add_argument("--functions", action="store_true", help="emit pure-function candidates for /fuzz")
    p.add_argument("--exclude", nargs="*", default=[], help="extra ignore globs/prefixes")
    p.set_defaults(func=cmd_census)

    p = sub.add_parser("hotspots", help="rank files by likelihood-of-defect")
    p.add_argument("--top", type=int, default=20)
    p.add_argument("--since", default=None, help="churn window, e.g. '6 months ago'")
    p.add_argument("--exclude", nargs="*", default=[])
    p.set_defaults(func=cmd_hotspots)

    p = sub.add_parser("signals", help="pain-point pre-pass: TODO age, flags, config drift")
    p.add_argument("--max-age-days", type=int, default=180)
    p.add_argument("--exclude", nargs="*", default=[])
    p.set_defaults(func=cmd_signals)

    p = sub.add_parser("deps", help="dependency audit (offline; --osv for advisories)")
    p.add_argument("--osv", action="store_true", help="query OSV.dev (network, opt-in)")
    p.set_defaults(func=cmd_deps)

    p = sub.add_parser("merge", help="validate+fingerprint+dedupe+suppress+baseline findings")
    p.add_argument("inputs", nargs="+", help="findings JSON files, or - for stdin")
    p.add_argument("--baseline", default=None, help=f"default: {STATE_DIR}/baseline.json")
    p.add_argument("--suppress", default=None, help=f"default: {STATE_DIR}/suppressions.json")
    p.add_argument("--write-baseline", action="store_true")
    p.add_argument("--out", default=None, help=f"default: {STATE_DIR}/findings.json")
    p.add_argument("--fail-on", choices=["critical-high", "any", "none"], default="critical-high")
    p.add_argument("--no-cluster", action="store_true",
                   help="keep cross-lens duplicates separate (legacy: boost confidence, don't merge)")
    p.set_defaults(func=cmd_merge)

    p = sub.add_parser("render", help="findings JSON -> md/html/sarif")
    p.add_argument("input", help="findings JSON file, or - for stdin")
    p.add_argument("--formats", default="md,html,sarif")
    p.add_argument("--md", default=None)
    p.add_argument("--html", default=None)
    p.add_argument("--sarif", default=None)
    p.set_defaults(func=cmd_render)

    p = sub.add_parser("diff", help="fingerprint-compare two findings JSON files")
    p.add_argument("a")
    p.add_argument("b")
    p.set_defaults(func=cmd_diff)

    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
